# Generated by Django 5.2 on 2025-05-05 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='name',
            new_name='portfolio_name',
        ),
        migrations.RemoveField(
            model_name='stocks_followed',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='stocks_followed',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stocks_followed', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocks_followed',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stocks_symbols',
            name='ticker',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
