# Generated by Django 5.2 on 2025-05-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_name_portfolio_portfolio_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks_followed',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocks_followed',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocks_followed',
            name='mid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocks_followed',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocks_followed',
            name='prevClose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocks_followed',
            name='tngolast',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocks_followed',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
