# Generated by Django 5.2 on 2025-05-06 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alertrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stocks_followed',
            constraint=models.UniqueConstraint(fields=('user', 'ticker'), name='unique_user_ticker'),
        ),
    ]
