# Generated by Django 5.2 on 2025-05-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_stocks_followed_unique_user_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='greater',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='sleeping',
            field=models.BooleanField(default=False),
        ),
    ]
